data:
  data_dir: "data/raw"
  img_size: [384, 384]
  crop_bbox: true
  num_workers: 4

model:
  name: "convnext_small.fb_in22k_ft_in1k_384"
  pretrained: true
  drop_rate: 0.4      # УВЕЛИЧЕНО с 0.2: Жестче глушим нейроны, чтобы не заучивала трейн
  init_bias: 2.88     # ИЗМЕНЕНО: Ставим точное среднее значение из твоей статистики

train:
  loss_name: "wing"   # ИЗМЕНЕНО: Переходим на Wing Loss!
  batch_size: 16
  epochs: 50
  lr: 5.0e-5            # УМЕНЬШЕНО с 1e-4: Для Wing Loss нужен шаг поменьше
  weight_decay: 0.05  # УВЕЛИЧЕНО с 0.01: Сильнее штрафуем веса за переобучение
  warmup_epochs: 5    # УВЕЛИЧЕНО: Даем больше времени на разогрев
  patience: 10
  save_dir: "checkpoints"
  use_wandb: true
  wandb_project: "cow_bcs"
  wandb_name: "run_02_wing_loss_reg"